RJozwiak\Libroteca\Domain\Model\Book\Book:
  read_only: true
  properties:
    id:
      type: string
    isbn:
      type: string
      exclude_if: 'object.isbn().isbn() == null'
    authors:
      type: array<string>
    title:
      type: string
