version: "3"

services:
  # front: TODO

  app:
    build: docker/lumen
    container_name: libroteca-web
    restart: always
    depends_on:
      - db
    environment:
      FRAMEWORK: lumen
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    volumes:
      - .:/var/www/libroteca:rw
    working_dir: /var/www/libroteca

  db:
    image: bitnami/mongodb:3.4.7-r0
    container_name: libroteca-db
    restart: always
    ports:
      - "27018:27017"
    networks:
      - backend
    environment:
      MONGODB_DATABASE: libroteca_db
      MONGODB_USERNAME: libroteca
      MONGODB_PASSWORD: libroteca
    volumes:
      - db-data:/data/db

   # cache: TODO

volumes:
  db-data: # default

networks:
  frontend: # default
  backend: # default
