version: "3"

services:
  front-app:
    build: frontend/docker
    restart: always
    depends_on:
      - web-app
    ports:
      - "3000:3000"
    networks:
      - frontend
    volumes:
      - ./frontend:/usr/src/libroteca
    working_dir: /usr/src/libroteca

  web-app:
    build: docker/lumen
    restart: always
    depends_on:
      - db
    environment:
      FRAMEWORK: lumen
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    volumes:
      - .:/var/www/libroteca:rw
    working_dir: /var/www/libroteca

  db:
    image: bitnami/mongodb:3.4.7-r0
    restart: always
    ports:
      - "27018:27017"
    networks:
      - backend
    environment:
      MONGODB_DATABASE: libroteca_db
      MONGODB_USERNAME: libroteca
      MONGODB_PASSWORD: libroteca
    volumes:
      - db-data:/data/db

   # cache: TODO

volumes:
  db-data: # default

networks:
  frontend: # default
  backend: # default
