RJozwiak\Libroteca\Domain\Model\BookLoan\BookLoan:
  type: entity
  table: book_loans
  repositoryClass: RJozwiak\Libroteca\Infrastructure\Domain\Model\BookLoan\DoctrineBookLoanRepository
  id:
    id:
      column: id
      type: BookLoanID
  fields:
    bookCopyID:
      column: book_copy_id
      type: BookCopyID
    readerID:
      column: reader_id
      type: ReaderID
    dueDate:
      column: due_date
      type: date_immutable
    ended:
      column: has_ended
      type: boolean
    endDate:
      column: end_date
      type: datetime_immutable
    prolonged:
      column: is_prolonged
      type: boolean
    remarks:
      column: remarks
      type: string
