CREATE TABLE IF NOT EXISTS books(
  id UUID PRIMARY KEY,
  title VARCHAR NOT NULL,
  isbn VARCHAR(13) NOT NULL,
  authors TEXT[] NOT NULL
);

CREATE TABLE IF NOT EXISTS readers(
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS book_copies(
  id UUID PRIMARY KEY,
  book_id UUID REFERENCES books(id) NOT NULL,
  remarks VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS book_loans(
  id UUID PRIMARY KEY,
  book_copy_id UUID REFERENCES book_copies(id) NOT NULL,
  reader_id UUID REFERENCES readers(id) NOT NULL,
  due_date TIMESTAMP NOT NULL,
  has_ended BOOLEAN NOT NULL,
  end_date TIMESTAMP NOT NULL,
  is_prolonged BOOLEAN NOT NULL,
  remarks VARCHAR(1024)
);
