imports:
  - { resource: database.yml }
  - { resource: email.yml }
  - { resource: parameters.yml }

parameters:
  # TODO: group & split into files

  request.class: Symfony\Component\HttpFoundation\Request
  request_stack.class: Symfony\Component\HttpFoundation\RequestStack
  request_context.class: Symfony\Component\Routing\RequestContext

  doctrine.book_repository.class: RJozwiak\Libroteca\Infrastructure\Domain\Model\Book\DoctrineBookRepository
  doctrine.book_copy_repository.class: RJozwiak\Libroteca\Infrastructure\Domain\Model\BookCopy\DoctrineBookCopyRepository
  doctrine.book_loan_repository.class: RJozwiak\Libroteca\Infrastructure\Domain\Model\BookLoan\DoctrineBookLoanRepository
  doctrine.reader_repository.class: RJozwiak\Libroteca\Infrastructure\Domain\Model\Reader\DoctrineReaderRepository

  book.class: RJozwiak\Libroteca\Domain\Model\Book\Book
  book_copy.class: RJozwiak\Libroteca\Domain\Model\BookCopy\BookCopy
  book_loan.class: RJozwiak\Libroteca\Domain\Model\BookLoan\BookLoan
  reader.class: RJozwiak\Libroteca\Domain\Model\Reader\Reader

  isbn_factory.class: RJozwiak\Libroteca\Domain\Model\Book\ISBN\ISBNFactory
  book_loan_factory.class: RJozwiak\Libroteca\Domain\Model\BookLoan\BookLoanFactory
  books_import_file_loader.class: RJozwiak\Libroteca\Infrastructure\Application\Command\CsvFileLoader

  lend_book_copy_handler.class: RJozwiak\Libroteca\Application\Command\LendBookCopyHandler
  prolong_book_loan_handler.class: RJozwiak\Libroteca\Application\Command\ProlongBookLoanHandler
  end_book_loan_handler.class: RJozwiak\Libroteca\Application\Command\EndBookLoanHandler
  register_book_handler.class: RJozwiak\Libroteca\Application\Command\RegisterBookHandler
  register_book_copy_handler.class: RJozwiak\Libroteca\Application\Command\RegisterBookCopyHandler
  register_reader_handler.class: RJozwiak\Libroteca\Application\Command\RegisterReaderHandler
  update_book_handler.class: RJozwiak\Libroteca\Application\Command\UpdateBookHandler
  update_book_copy_remarks_handler.class: RJozwiak\Libroteca\Application\Command\UpdateBookCopyRemarksHandler
  import_books_handler.class: RJozwiak\Libroteca\Application\Command\ImportBooksHandler
  send_notification_to_reader_handler.class: RJozwiak\Libroteca\Application\Command\SendNotificationToReaderHandler

  tactician.command_bus.class: League\Tactician\CommandBus
  tactician.method_name_inflector.class: RJozwiak\Libroteca\Infrastructure\Application\CommandBus\Tactician\MethodNameInflector\ExecuteInflector
  tactician.in_memory_locator.class: RJozwiak\Libroteca\Infrastructure\Application\CommandBus\Tactician\Locator\InMemoryHandlerLocator
  tactician.command_class_name_extractor.class: League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor
  tactician.command_handler_middleware.class: League\Tactician\Handler\CommandHandlerMiddleware
  tactician.doctrine_transaction_middleware.class: League\Tactician\Doctrine\ORM\TransactionMiddleware

  entity_manager.class: Doctrine\ORM\EntityManager
  entity_manager_factory.class: RJozwiak\Libroteca\Infrastructure\Persistence\Doctrine\EntityManagerFactory
  doctrine.connection.class: Doctrine\DBAL\Connection
  doctrine.dbal.expression_builder.class: Doctrine\DBAL\Query\Expression\ExpressionBuilder

  expression_language.class: Symfony\Component\ExpressionLanguage\ExpressionLanguage

  jms_serializer.class: JMS\Serializer\Serializer
  jms_serializer_builder.class: JMS\Serializer\SerializerBuilder
  jms_expression_evaluator.class: JMS\Serializer\Expression\ExpressionEvaluator

  # TODO: cache services to allow `abstract` service definition
  base_doctrine_query_service.class: RJozwiak\Libroteca\Infrastructure\Application\Query\Doctrine\BaseDoctrineQueryService
  doctrine_reader_query_service.class: RJozwiak\Libroteca\Infrastructure\Application\Query\Doctrine\DoctrineReaderQueryService
  doctrine_book_query_service.class: RJozwiak\Libroteca\Infrastructure\Application\Query\Doctrine\DoctrineBookQueryService
  doctrine_book_copy_query_service.class: RJozwiak\Libroteca\Infrastructure\Application\Query\Doctrine\DoctrineBookCopyQueryService
  doctrine_book_loan_query_service.class: RJozwiak\Libroteca\Infrastructure\Application\Query\Doctrine\DoctrineBookLoanQueryService

  dbal_expression_factory.class: RJozwiak\Libroteca\Infrastructure\Application\Query\Doctrine\Specification\DBAL\DBALExpressionFactory
  orm_expression_factory.class: RJozwiak\Libroteca\Infrastructure\Application\Query\Doctrine\Specification\ORM\ORMExpressionFactory

  email.class: RJozwiak\Libroteca\Domain\Model\Reader\Email
  email_notifier.class: RJozwiak\Libroteca\Infrastructure\Domain\Model\Reader\Notification\Email\Adapter\SwiftMailerNotifier
  email_notification_builder.class: RJozwiak\Libroteca\Infrastructure\Domain\Model\Reader\Notification\Email\Adapter\TwigEmailNotificationBuilder
  email_notification_template_builder.class: RJozwiak\Libroteca\Infrastructure\Domain\Model\Reader\Notification\Email\EmailNotificationTemplateBuilder
  notifier_provider.class: RJozwiak\Libroteca\Domain\Model\Reader\MembershipBasedNotifierProvider
  notification_builder_factory.class: RJozwiak\Libroteca\Infrastructure\Domain\Model\Reader\Notification\NotificationBuilderFactory
  notification_template_builder_factory.class: RJozwiak\Libroteca\Infrastructure\Domain\Model\Reader\Notification\NotificationTemplateBuilderFactory
  notification_sender.class: RJozwiak\Libroteca\Domain\Model\Reader\Notification\NotificationSender

  swift_transport.class: Swift_SmtpTransport
  swift_mailer.class: Swift_Mailer

services:
  request:
    class: '%request.class%'
    factory: ['%request.class%', createFromGlobals]
  request_stack:
    class: '%request_stack.class%'
  request_context:
    class: '%request_context.class%'

  book_repository:
    class: '%doctrine.book_repository.class%'
    factory: ['@entity_manager', getRepository]
    arguments:
      - '%book.class%'
  book_copy_repository:
    class: '%doctrine.book_copy_repository.class%'
    factory: ['@entity_manager', getRepository]
    arguments:
      - '%book_copy.class%'
  book_loan_repository:
    class: '%doctrine.book_loan_repository.class%'
    factory: ['@entity_manager', getRepository]
    arguments:
      - '%book_loan.class%'
  reader_repository:
    class: '%doctrine.reader_repository.class%'
    factory: ['@entity_manager', getRepository]
    arguments:
      - '%reader.class%'

  isbn_factory:
    class: '%isbn_factory.class%'
  book_loan_factory:
    class: '%book_loan_factory.class%'
    arguments:
      - '@book_loan_repository'
  books_import_file_loader:
    class: '%books_import_file_loader.class%'

  lend_book_copy_handler:
    class: '%lend_book_copy_handler.class%'
    arguments:
      - '@reader_repository'
      - '@book_copy_repository'
      - '@book_loan_repository'
      - '@book_loan_factory'
  prolong_book_loan_handler:
    class: '%prolong_book_loan_handler.class%'
    arguments:
      - '@book_loan_repository'
  end_book_loan_handler:
    class: '%end_book_loan_handler.class%'
    arguments:
      - '@book_loan_repository'
  register_book_handler:
    class: '%register_book_handler.class%'
    arguments:
      - '@isbn_factory'
      - '@book_repository'
  register_book_copy_handler:
    class: '%register_book_copy_handler.class%'
    arguments:
      - '@book_repository'
      - '@book_copy_repository'
  register_reader_handler:
    class: '%register_reader_handler.class%'
    arguments:
      - '@reader_repository'
  update_book_handler:
    class: '%update_book_handler.class%'
    arguments:
      - '@isbn_factory'
      - '@book_repository'
  update_book_copy_remarks_handler:
    class: '%update_book_copy_remarks_handler.class%'
    arguments:
      - '@book_copy_repository'
  import_books_handler:
    class: '%import_books_handler.class%'
    arguments:
      - '@isbn_factory'
      - '@book_repository'
      - '@book_copy_repository'
      - '@books_import_file_loader'
  send_notification_to_reader_handler:
    class: '%send_notification_to_reader_handler.class%'
    arguments:
      - '@reader_repository'
      - '@notifier_provider'
      - '@notification_sender'

  tactician.method_name_inflector:
    class: '%tactician.method_name_inflector.class%'
  tactician.in_memory_locator:
    class: '%tactician.in_memory_locator.class%'
    arguments:
      -
        - '@lend_book_copy_handler'
        - '@prolong_book_loan_handler'
        - '@register_book_handler'
        - '@register_book_copy_handler'
        - '@register_reader_handler'
        - '@end_book_loan_handler'
        - '@update_book_handler'
        - '@update_book_copy_remarks_handler'
        - '@import_books_handler'
        - '@send_notification_to_reader_handler'
  tactician.command_class_name_extractor:
    class: '%tactician.command_class_name_extractor.class%'
  tactician.command_handler_middleware:
    class: '%tactician.command_handler_middleware.class%'
    arguments:
      - '@tactician.command_class_name_extractor'
      - '@tactician.in_memory_locator'
      - '@tactician.method_name_inflector'
  tactician.doctrine_transaction_middleware:
    class: '%tactician.doctrine_transaction_middleware.class%'
    arguments:
      - '@entity_manager'
  command_bus:
    class: '%tactician.command_bus.class%'
    arguments:
      -
        - '@tactician.doctrine_transaction_middleware'
        - '@tactician.command_handler_middleware'

  entity_manager:
    class: '%entity_manager.class%'
    factory: ['%entity_manager_factory.class%', create]
    arguments:
      - driver: '%database_driver%'
        host: '%database_host%'
        user: '%database_username%'
        password: '%database_password%'
        dbname: '%database_name%'
  doctrine.connection:
    class: '%doctrine.connection.class%'
    factory: ['@entity_manager', getConnection]
  doctrine.dbal.expression_builder:
    class: '%doctrine.dbal.expression_builder.class%'
    factory: ['@doctrine.connection', getExpressionBuilder]

  expression_language:
    class: '%expression_language.class%'

  jms_serializer_builder:
    class: '%jms_serializer_builder.class%'
    factory: ['%jms_serializer_builder.class%', create]
    calls:
      - method: setCacheDir
        arguments:
          - '%jms_serializer_cache_dir%'
      - method: addMetadataDir
        arguments:
          - '%jms_serializer.metadata_dir%'
      - method: setDebug
        arguments: ['%kernel.debug%']
      - method: setExpressionEvaluator
        arguments: ['@jms_expression_evaluator']
  jms_serializer:
    class: '%jms_serializer.class%'
    factory: ['@jms_serializer_builder', build]
  jms_expression_evaluator:
    class: '%jms_expression_evaluator.class%'
    arguments:
      - '@expression_language'

  doctrine_reader_query_service:
    class: '%doctrine_reader_query_service.class%'
    arguments:
      - '@entity_manager'
      - '@dbal_expression_factory'
  doctrine_book_query_service:
    class: '%doctrine_book_query_service.class%'
    arguments:
      - '@entity_manager'
      - '@jms_serializer'
      - '@orm_expression_factory'
  doctrine_book_copy_query_service:
    class: '%doctrine_book_copy_query_service.class%'
    arguments:
      - '@entity_manager'
      - '@jms_serializer'
  doctrine_book_loan_query_service:
    class: '%doctrine_book_loan_query_service.class%'
    arguments:
      - '@entity_manager'
      - '@jms_serializer'

  dbal_expression_factory:
    class: '%dbal_expression_factory.class%'
    arguments:
      - '@doctrine.dbal.expression_builder'
  orm_expression_factory:
    class: '%orm_expression_factory.class%'
    arguments:
      - '@doctrine.dbal.expression_builder'

  no_reply_email:
    class: '%email.class%'
    arguments:
      - '%email.username%'
  email_notifier:
    class: '%email_notifier.class%'
    arguments:
      - '@swift_mailer'
      - '@no_reply_email'
  email_notification_builder:
    class: '%email_notification_builder.class%'
  email_notification_template_builder:
    class: '%email_notification_template_builder.class%'
  notifier_provider:
    class: '%notifier_provider.class%'
    arguments:
      - '@email_notifier'
      - '@email_notifier'
  notification_builder_factory:
    class: '%notification_builder_factory.class%'
  notification_template_builder_factory:
    class: '%notification_template_builder_factory.class%'
  notification_sender:
    class: '%notification_sender.class%'
    arguments:
      - '@notification_template_builder_factory'
      - '@notification_builder_factory'

  swift_transport:
    class: '%swift_transport.class%'
    arguments:
      - '%email.host%'
      - '%email.port%'
      - '%email.encryption%'
    calls:
      - method: setUsername
        arguments:
          - '%email.username%'
      - method: setPassword
        arguments:
          - '%email.password%'
  swift_mailer:
    class: '%swift_mailer.class%'
    arguments:
      - '@swift_transport'
